config/routes.rb
TodoApp::Application.routes.draw do

  shallow do
    resources :users, only: [:new, :create, :show] do
      resources :goals
    end
  end
  resource :session, only: [:new, :create, :destroy]

  resources :goals, only: [:index]
end

app/models/goal.rb
class Goal < ActiveRecord::Base

  belongs_to :author, class_name: "User", foreign_key: :user_id

  def accomplished?
    !!@accomplished_status
  end

  def public?
    !!@public_status
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  attr_reader :password

  has_many :goals, class_name: "Goal", foreign_key: :user_id

  validates :username, :password_digest, :session_token, presence: true
  validates :username, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  before_validation :ensure_session_token

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save
    self.session_token
  end

  def password=(word)
    @password = word
    self.password_digest = encrypt(word)
  end

  def encrypt(word)
    BCrypt::Password.create(word)
  end

  def is_password?(secret)
    BCrypt::Password.new(self.password_digest).is_password?(secret)
  end


  private

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :ensure_signed_in

  helper_method :signed_in?, :current_user

  def current_user
    User.find_by(session_token: session[:token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in_user(user)
    session[:token] = user.reset_session_token!
  end


  private

  def ensure_signed_in
    redirect_to new_session_url unless signed_in?
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  def index

  end

  def create
    @goal = Goal.new(goal_params)
    @goal.author = current_user
    if @goal.save
      redirect_to user_url(@goal.author)
    else
      flash[:errors] = @goal.errors.full_messages
      redirect_to user_url(@goal.author)
    end
  end


  private

  def goal_params
    params.require(:goal).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_filter :ensure_signed_in, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(username: params[:user][:username])
    if @user && @user.is_password?(params[:user][:password])
      sign_in_user(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Invalid Credentials"]
      @user = User.new(password: params[:user][:password],
                        username: params[:user][:username])
      render :new
    end
  end

  def destroy
    current_user.reset_session_token!
    session[:token] = nil
    redirect_to new_session_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_filter :ensure_signed_in, only: [:new, :create]

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in_user(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @goal = @user.goals.new
    render :show
  end

  private

  def user_params
    params.require(:user).permit(:password, :username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/_form.html.erb
<form action="<%= user_goals_url(user) %>" method="POST">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <label for="goal_title">Title</label>
  <input type="text"
          name="goal[title]"
          value="<%= goal.title %>"
          id="goal_title">


  <label for="goal_body">Description</label>
  <input type="text"
          name="goal[body]"
          value="<%= goal.body %>"
          id="goal_body">

  <input type="submit" value="Create Goal">

</form>

app/views/layouts/_nav_header.html.erb
<nav>

  <logo>
    <%= render "layouts/sign_in_status" %>
  </logo>

  <ul class="group">
    <li><a href="
      <%= user_url(current_user) if signed_in? %>">Home</li></a>
    <li><a href="<%= users_url %>">Users</li></a>
    <li><a href="<%= goals_url %>">Goals</li></a>
  </ul>

</nav>

app/views/layouts/_sign_in_status.html.erb
<% if signed_in? %>
  <h1 class="group"><%= current_user.username %></h1>
  <form action="/session" method="POST">
    <input type="hidden" name="_method" value="delete">

    <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

    <input type="submit" value="Logout">

  </form>

<% else %>

  <login>
    <a href="<%= new_session_url %>">Come Back!</a>
    <a href="<%= new_user_url %>">Join Us!</a>
  </login>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoApp</title>
  <%= csrf_meta_tags %>

  <style>

  html, body, ul, li, a, p, h1 {
    margin: 0;
    padding: 0;
    border: 0;
    font: inherit;
  }

  body {
    font-family: sans-serif;
    background: lightgreen;
  }

  .group:after {
    content: "";
    display: block;
    clear: both;
  }

  nav {
    margin: auto;
    float: left;
    background: darkorange;
    display: block;
    width: 100%;
  }

  li {
    list-style: none;
  }

  nav ul  {
    display: block;
    float: right;
  }

  nav li {
    display: block;
    border-left: 5px dotted blue;
    float: left;
  }

  nav a {
    display: block;
    padding: 20px;
    color: lightyellow;
    text-decoration: none;
  }

  nav a:hover {
    background: black;
  }

  logo {
    display: block;
    float:left;
  }

  logo h1 {
    padding: 5px;
  }

  form input[type="submit"] {
    border: 0;
    padding: 20;
    color: black;
    background: yellow;
  }

  form input[type="submit"]:hover {
    background: black;
    color: darkorange;
  }

  login a {
    display: block;
    float: left;
    border-right: 5px dotted green;
  }

  login a:hover {
    background: yellow;
    color: darkgreen;
  }

  </style

</head>
<body>


  <%= render "layouts/nav_header" %>
  <br>
  <% if flash.now[:errors] %>
    <% flash.now[:errors].each do |error| %>
      <ul>
        <li><%= error %></li>
      </ul>
    <% end %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%=  users_url %>" method="post">
  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <label for="username">Username</label>
    <input id="username"
           type="text"
           value="<%= @user.username %>"
           name="user[username]">

  <label for="password">Password</label>
    <input id="password"
          type="password"
          name="user[password]">

  <input type="submit" value="Sign Up">

</form>

app/views/users/show.html.erb
<h1>Your Goals</h1>

<h2><marquee>Add a Goal</marquee></h2>

<%= render "/goals/form", user: @user, goal: @goal %>